@startuml entity_relations
digraph foo {

    overlap=false;

    { node [shape=box style=filled fillcolor="#5555dd" fontcolor="white"]
		Company Member Group Livestream SocialChannel MediaChannel SocialPlatform MediaPlatform
	}

    { node [shape=diamond]
        "is organized in" "employs many" "has many" "hosts many" "has Account on" "is on" "is part of" "is hosted on"
    }

    Company -> "is organized in" -> Group
    Company -> "employs many" -> Member

    Group -> "has many" -> Member

    Member -> "hosts many" -> Livestream
    Member -> "has Account on" -> {MediaChannel SocialChannel}

    SocialChannel -> "is on" -> SocialPlatform
    MediaChannel -> "is part of" -> MediaPlatform

    Livestream -> "is hosted on" -> MediaChannel
}
@enduml                     